openapi: 3.0.3
info:
  title: Booking API
  description: Booking API service
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /customer:
    get:
      responses:
        "200":
          description: URL and requests json schema
          content:
            application/json:
              schema:
                type: string

  /customer/all_customers:
    get:
      responses:
        "200":
          description: All customers list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    contacts:
                      type: string
                    tickets:
                      type: array

  /customer/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Search exact customer by his id
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  contacts:
                    type: string
                  tickets:
                    type: array
        "404":
          description: Customer with id={id} not found

  /customer/name/{name}:
    get:
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Search all customers with names containing request string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    contacts:
                      type: string
                    tickets:
                      type: array
  
  /customer/new:
    post:
      parameters:
        - in: query
          name: name
          required: true
          content:
            application/json:
              schema:
                type: string
      responses:
        "200":
          description: Create new customer
