openapi: 3.0.3
info:
  title: Booking API
  description: Booking API service
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /customer:
    get:
      responses:
        "200":


  
